"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { BadgeCheck, CircleDollarSign, Clock3, Loader2, MessageCircle, Plus, RefreshCw, Search, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { Field } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { LoadingBlock } from "@/components/ui/loading";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { approvalChannelLabels, approvalStatusLabels } from "@/lib/domain/labels";
import type { ApprovalChannel, ApprovalStatus, WorkOrderStatus } from "@/lib/domain/types";
import { formatDateTime, formatMoney } from "@/lib/utils";

type WorkOrderOption = {
  id: string; work_order_number: string; complaint: string; status: WorkOrderStatus; grand_total: number;
  customers: { full_name: string; phone: string };
  vehicles: { make: string; model: string; model_year: number; plate_number: string | null };
  work_order_approvals: Array<{ id: string; status: ApprovalStatus }>;
};
type ApprovalRow = {
  id: string; work_order_id: string; requested_amount: number; items_summary: string; status: ApprovalStatus;
  channel: ApprovalChannel; response_note: string | null; customer_visible: boolean; requested_at: string; responded_at: string | null;
  customers: { full_name: string; phone: string };
  work_orders: { work_order_number: string; status: WorkOrderStatus; vehicles: { make: string; model: string; model_year: number; plate_number: string | null } };
};
type RequestForm = { workOrderId: string; requestedAmount: string; itemsSummary: string; channel: ApprovalChannel; customerVisible: boolean };
type DecisionForm = { status: "approved" | "rejected" | "cancelled"; channel: ApprovalChannel; responseNote: string };

const emptyRequest: RequestForm = { workOrderId: "", requestedAmount: "0", itemsSummary: "", channel: "whatsapp", customerVisible: true };
const emptyDecision: DecisionForm = { status: "approved", channel: "whatsapp", responseNote: "" };

function tone(status: ApprovalStatus) { if (status === "approved") return "success" as const; if (status === "rejected" || status === "cancelled") return "danger" as const; return "warning" as const; }

export function ApprovalsManager() {
  const [rows, setRows] = useState<ApprovalRow[]>([]); const [orders, setOrders] = useState<WorkOrderOption[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [search, setSearch] = useState(""); const [status, setStatus] = useState<ApprovalStatus | "all">("all"); const [requestOpen, setRequestOpen] = useState(false); const [requestForm, setRequestForm] = useState<RequestForm>(emptyRequest); const [decisionTarget, setDecisionTarget] = useState<ApprovalRow | null>(null); const [decisionForm, setDecisionForm] = useState<DecisionForm>(emptyDecision);

  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/admin/approvals", { cache: "no-store" }); const body = await response.json(); if (!response.ok || !body.ok) throw new Error(body.error ?? "تعذر تحميل الموافقات"); setRows(body.data.approvals); setOrders(body.data.workOrders); } catch (cause) { setError(cause instanceof Error ? cause.message : "تعذر تحميل الموافقات"); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);

  const eligibleOrders = useMemo(() => orders.filter((order) => !order.work_order_approvals?.some((approval) => approval.status === "pending")), [orders]);
  const filtered = useMemo(() => { const term = search.trim().toLowerCase(); return rows.filter((row) => (status === "all" || row.status === status) && (!term || [row.work_orders.work_order_number, row.customers.full_name, row.customers.phone, row.work_orders.vehicles.make, row.work_orders.vehicles.model, row.items_summary].some((value) => value.toLowerCase().includes(term)))); }, [rows, search, status]);

  function openRequest() { const first = eligibleOrders[0]; setRequestForm({ ...emptyRequest, workOrderId: first?.id ?? "", requestedAmount: first ? String(first.grand_total ?? 0) : "0" }); setRequestOpen(true); setError(""); }
  function onSelectOrder(id: string) { const selected = eligibleOrders.find((order) => order.id === id); setRequestForm((current) => ({ ...current, workOrderId: id, requestedAmount: selected ? String(selected.grand_total ?? 0) : current.requestedAmount, itemsSummary: selected?.complaint ?? current.itemsSummary })); }
  async function submitRequest(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const response = await fetch("/api/admin/approvals", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(requestForm) }); const body = await response.json(); if (!response.ok || !body.ok) throw new Error(body.error ?? "تعذر إنشاء طلب الموافقة"); setRequestOpen(false); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "تعذر إنشاء طلب الموافقة"); } finally { setBusy(false); } }
  function openDecision(row: ApprovalRow, decision: DecisionForm["status"]) { setDecisionTarget(row); setDecisionForm({ ...emptyDecision, status: decision, channel: row.channel }); setError(""); }
  async function submitDecision(event: React.FormEvent) { event.preventDefault(); if (!decisionTarget) return; setBusy(true); setError(""); try { const response = await fetch(`/api/admin/approvals/${decisionTarget.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(decisionForm) }); const body = await response.json(); if (!response.ok || !body.ok) throw new Error(body.error ?? "تعذر تسجيل القرار"); setDecisionTarget(null); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "تعذر تسجيل القرار"); } finally { setBusy(false); } }

  return <>
    <div className="mb-5 flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-1 flex-col gap-3 sm:flex-row"><div className="relative max-w-xl flex-1"><Search className="pointer-events-none absolute right-4 top-1/2 -translate-y-1/2 text-[#727986]" size={18} /><Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="رقم الأمر أو العميل أو السيارة" className="pr-11" /></div><Select value={status} onChange={(e) => setStatus(e.target.value as typeof status)} className="sm:max-w-52"><option value="all">كل القرارات</option><option value="pending">بانتظار القرار</option><option value="approved">موافق</option><option value="rejected">مرفوض</option><option value="cancelled">ملغي</option></Select></div><div className="flex gap-2"><Button variant="secondary" onClick={() => void load()}><RefreshCw size={17} /> تحديث</Button><Button onClick={openRequest} disabled={!eligibleOrders.length}><Plus size={18} /> طلب موافقة</Button></div></div>
    {!eligibleOrders.length && !loading ? <div className="mb-4 rounded-xl border border-[#FFD100]/15 bg-[#FFD100]/5 p-3 text-sm text-[#d8d1a0]">لا توجد أوامر في مرحلة التشخيص قابلة لإنشاء طلب جديد، أو يوجد طلب معلق بالفعل.</div> : null}
    {error ? <div className="mb-4 rounded-xl border border-red-400/20 bg-red-400/8 p-3 text-sm text-red-200">{error}</div> : null}
    {loading ? <LoadingBlock label="جاري تحميل الموافقات" /> : filtered.length ? <div className="grid gap-4 xl:grid-cols-2">{filtered.map((row) => <article key={row.id} className="panel rounded-2xl p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-black">{row.work_orders.work_order_number}</h3><Badge tone={tone(row.status)}>{approvalStatusLabels[row.status]}</Badge></div><p className="mt-2 text-sm text-[#aeb4bd]">{row.customers.full_name} — {row.work_orders.vehicles.make} {row.work_orders.vehicles.model} {row.work_orders.vehicles.model_year}</p><p className="mt-1 text-xs text-[#737b87]" dir="ltr">{row.customers.phone}</p></div><div className="text-left"><span className="text-xs text-[#737b87]">القيمة المطلوبة</span><strong className="mt-1 block text-xl text-[#FFD100]">{formatMoney(row.requested_amount)}</strong></div></div><div className="mt-5 rounded-xl bg-white/[0.035] p-4"><span className="text-xs font-bold text-[#8f96a3]">ملخص الأعمال</span><p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-[#d4d7dc]">{row.items_summary}</p></div><div className="mt-4 flex flex-wrap items-center gap-x-5 gap-y-2 text-xs text-[#7f8793]"><span className="flex items-center gap-1"><MessageCircle size={14} /> {approvalChannelLabels[row.channel]}</span><span className="flex items-center gap-1"><Clock3 size={14} /> {formatDateTime(row.requested_at)}</span><span>{row.customer_visible ? "ظاهر في بوابة العميل" : "داخلي"}</span></div>{row.response_note ? <p className="mt-4 rounded-xl border border-white/6 p-3 text-sm leading-7 text-[#aeb4bd]">{row.response_note}</p> : null}{row.status === "pending" ? <div className="mt-5 grid grid-cols-3 gap-2"><Button size="sm" onClick={() => openDecision(row, "approved")}><BadgeCheck size={16} /> موافق</Button><Button size="sm" variant="danger" onClick={() => openDecision(row, "rejected")}>مرفوض</Button><Button size="sm" variant="secondary" onClick={() => openDecision(row, "cancelled")}>إلغاء الطلب</Button></div> : null}</article>)}</div> : <EmptyState title="لا توجد موافقات" description="أنشئ طلب موافقة من أمر عمل في مرحلة التشخيص." />}

    {requestOpen ? <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-black/75 p-4"><button className="absolute inset-0" onClick={() => !busy && setRequestOpen(false)} aria-label="إغلاق" /><form onSubmit={submitRequest} className="panel relative z-10 my-8 w-full max-w-2xl rounded-3xl bg-[#111318] p-5 sm:p-7"><button type="button" onClick={() => setRequestOpen(false)} className="absolute left-4 top-4 grid size-9 place-items-center rounded-xl bg-white/5"><X size={18} /></button><h2 className="text-xl font-black">إنشاء طلب موافقة</h2><p className="mt-2 text-sm text-[#8f96a3]">يسجل عرض الأعمال ويحوّل أمر العمل إلى انتظار الموافقة.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><Field label="أمر العمل"><Select value={requestForm.workOrderId} onChange={(e) => onSelectOrder(e.target.value)} required><option value="" disabled>اختر أمر العمل</option>{eligibleOrders.map((order) => <option key={order.id} value={order.id}>{order.work_order_number} — {order.customers.full_name} — {order.vehicles.make} {order.vehicles.model}</option>)}</Select></Field></div><Field label="المبلغ المطلوب"><div className="relative"><CircleDollarSign className="pointer-events-none absolute right-4 top-1/2 -translate-y-1/2 text-[#727986]" size={18} /><Input type="number" min={0} step="0.01" value={requestForm.requestedAmount} onChange={(e) => setRequestForm({ ...requestForm, requestedAmount: e.target.value })} className="pr-11" required /></div></Field><Field label="قناة إرسال الطلب"><Select value={requestForm.channel} onChange={(e) => setRequestForm({ ...requestForm, channel: e.target.value as ApprovalChannel })}>{Object.entries(approvalChannelLabels).filter(([key]) => key !== "portal").map(([key, label]) => <option key={key} value={key}>{label}</option>)}</Select></Field><div className="sm:col-span-2"><Field label="ملخص الأعمال أو عرض السعر"><Textarea value={requestForm.itemsSummary} onChange={(e) => setRequestForm({ ...requestForm, itemsSummary: e.target.value })} required maxLength={5000} placeholder="مثال: استبدال كويل رقم 2 + تنظيف بخاخات + أجور العمل" /></Field></div><label className="sm:col-span-2 flex items-center gap-3 rounded-xl border border-[#343943] p-4 text-sm"><input type="checkbox" checked={requestForm.customerVisible} onChange={(e) => setRequestForm({ ...requestForm, customerVisible: e.target.checked })} className="size-5 accent-[#FFD100]" /> إظهار الطلب للعميل داخل بوابة العميل ليتمكن من الموافقة أو الرفض</label></div>{error ? <div className="mt-4 rounded-xl border border-red-400/20 bg-red-400/8 p-3 text-sm text-red-200">{error}</div> : null}<div className="mt-6 flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => setRequestOpen(false)} disabled={busy}>إلغاء</Button><Button type="submit" disabled={busy}>{busy ? <Loader2 className="animate-spin" size={17} /> : null}إنشاء الطلب</Button></div></form></div> : null}

    {decisionTarget ? <div className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-4"><button className="absolute inset-0" onClick={() => !busy && setDecisionTarget(null)} aria-label="إغلاق" /><form onSubmit={submitDecision} className="panel relative z-10 w-full max-w-lg rounded-3xl bg-[#111318] p-5 sm:p-7"><button type="button" onClick={() => setDecisionTarget(null)} className="absolute left-4 top-4 grid size-9 place-items-center rounded-xl bg-white/5"><X size={18} /></button><h2 className="text-xl font-black">تسجيل قرار العميل</h2><p className="mt-2 text-sm text-[#8f96a3]">{decisionTarget.work_orders.work_order_number} — {formatMoney(decisionTarget.requested_amount)}</p><div className="mt-6 grid gap-4"><Field label="القرار"><Select value={decisionForm.status} onChange={(e) => setDecisionForm({ ...decisionForm, status: e.target.value as DecisionForm["status"] })}><option value="approved">موافق</option><option value="rejected">مرفوض</option><option value="cancelled">إلغاء الطلب</option></Select></Field><Field label="قناة القرار"><Select value={decisionForm.channel} onChange={(e) => setDecisionForm({ ...decisionForm, channel: e.target.value as ApprovalChannel })}>{Object.entries(approvalChannelLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</Select></Field><Field label="ملاحظة أو إثبات القرار"><Textarea value={decisionForm.responseNote} onChange={(e) => setDecisionForm({ ...decisionForm, responseNote: e.target.value })} placeholder="مثال: وافق العميل عبر واتساب الساعة 4:15 م" /></Field></div>{error ? <div className="mt-4 rounded-xl border border-red-400/20 bg-red-400/8 p-3 text-sm text-red-200">{error}</div> : null}<div className="mt-6 flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => setDecisionTarget(null)} disabled={busy}>رجوع</Button><Button type="submit" disabled={busy}>{busy ? <Loader2 className="animate-spin" size={17} /> : null}حفظ القرار</Button></div></form></div> : null}
  </>;
}
