"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Clock3, Edit3, Loader2, Plus, RefreshCw, Search, Tags, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { Field } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { LoadingBlock } from "@/components/ui/loading";
import { Textarea } from "@/components/ui/textarea";
import { formatMoney } from "@/lib/utils";

type ServiceRow = { id: string; code: string; name_ar: string; description_ar: string | null; base_price: number | null; estimated_minutes: number | null; is_active: boolean; sort_order: number };
type FormState = { code: string; nameAr: string; descriptionAr: string; basePrice: string; estimatedMinutes: string; sortOrder: string; isActive: boolean };
const emptyForm: FormState = { code: "", nameAr: "", descriptionAr: "", basePrice: "", estimatedMinutes: "", sortOrder: "0", isActive: true };

function durationLabel(minutes: number | null) {
  if (!minutes) return "غير محدد";
  if (minutes < 60) return `${minutes} دقيقة`;
  const hours = Math.floor(minutes / 60); const rest = minutes % 60;
  return rest ? `${hours} ساعة و${rest} دقيقة` : `${hours} ساعة`;
}

export function ServicesManager() {
  const [rows, setRows] = useState<ServiceRow[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [search, setSearch] = useState(""); const [editing, setEditing] = useState<ServiceRow | null>(null); const [formOpen, setFormOpen] = useState(false); const [form, setForm] = useState<FormState>(emptyForm);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/admin/services", { cache: "no-store" }); const body = await response.json(); if (!response.ok || !body.ok) throw new Error(body.error ?? "تعذر تحميل الخدمات"); setRows(body.data); } catch (cause) { setError(cause instanceof Error ? cause.message : "تعذر تحميل الخدمات"); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const filtered = useMemo(() => { const term = search.trim().toLowerCase(); return rows.filter((row) => !term || [row.code, row.name_ar, row.description_ar ?? ""].some((value) => value.toLowerCase().includes(term))); }, [rows, search]);
  function openCreate() { setEditing(null); setForm(emptyForm); setFormOpen(true); setError(""); }
  function openEdit(row: ServiceRow) { setEditing(row); setForm({ code: row.code, nameAr: row.name_ar, descriptionAr: row.description_ar ?? "", basePrice: row.base_price == null ? "" : String(row.base_price), estimatedMinutes: row.estimated_minutes == null ? "" : String(row.estimated_minutes), sortOrder: String(row.sort_order), isActive: row.is_active }); setFormOpen(true); setError(""); }
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const response = await fetch(editing ? `/api/admin/services/${editing.id}` : "/api/admin/services", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const body = await response.json(); if (!response.ok || !body.ok) throw new Error(body.error ?? "تعذر حفظ الخدمة"); setFormOpen(false); setEditing(null); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "تعذر حفظ الخدمة"); } finally { setBusy(false); } }

  return <>
    <div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="relative max-w-xl flex-1"><Search className="pointer-events-none absolute right-4 top-1/2 -translate-y-1/2 text-[#727986]" size={18} /><Input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="ابحث باسم أو رمز الخدمة" className="pr-11" /></div><div className="flex gap-2"><Button variant="secondary" onClick={() => void load()}><RefreshCw size={17} /> تحديث</Button><Button onClick={openCreate}><Plus size={18} /> خدمة جديدة</Button></div></div>
    {error ? <div className="mb-4 rounded-xl border border-red-400/20 bg-red-400/8 p-3 text-sm text-red-200">{error}</div> : null}
    {loading ? <LoadingBlock label="جاري تحميل الخدمات" /> : filtered.length ? <div className="grid gap-4 lg:grid-cols-2 xl:grid-cols-3">{filtered.map((row) => <article key={row.id} className="panel rounded-2xl p-5"><div className="flex items-start gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-[#FFD100]/10 text-[#FFD100]"><Tags size={20} /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-black">{row.name_ar}</h3><Badge tone={row.is_active ? "success" : "neutral"}>{row.is_active ? "مفعلة" : "متوقفة"}</Badge></div><code dir="ltr" className="mt-1 block text-left text-xs text-[#7f8793]">{row.code}</code></div><Button variant="ghost" size="sm" onClick={() => openEdit(row)}><Edit3 size={17} /></Button></div><p className="mt-4 min-h-14 text-sm leading-7 text-[#9ca3af]">{row.description_ar || "لا يوجد وصف للخدمة."}</p><div className="mt-5 flex items-end justify-between border-t border-white/6 pt-4"><div><span className="block text-xs text-[#737b87]">السعر الأساسي</span><strong className="mt-1 block text-lg text-[#FFD100]">{row.base_price == null ? "حسب الفحص" : formatMoney(row.base_price)}</strong></div><div className="text-left"><span className="flex items-center gap-1 text-xs text-[#737b87]"><Clock3 size={14} /> المدة</span><strong className="mt-1 block text-sm">{durationLabel(row.estimated_minutes)}</strong></div></div></article>)}</div> : <EmptyState title="لا توجد خدمات" description="أضف الخدمات الفعلية وأسعارها ومددها لتظهر في الحجز." />}
    {formOpen ? <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-black/75 p-4"><button className="absolute inset-0" onClick={() => !busy && setFormOpen(false)} aria-label="إغلاق" /><form onSubmit={submit} className="panel relative z-10 my-8 w-full max-w-2xl rounded-3xl bg-[#111318] p-5 sm:p-7"><button type="button" onClick={() => setFormOpen(false)} className="absolute left-4 top-4 grid size-9 place-items-center rounded-xl bg-white/5"><X size={18} /></button><h2 className="text-xl font-black">{editing ? "تعديل الخدمة" : "إضافة خدمة"}</h2><p className="mt-2 text-sm text-[#8f96a3]">الأسعار والمدد هنا مرجعية للحجز والتشغيل ويمكن تعديلها لاحقًا.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="اسم الخدمة"><Input value={form.nameAr} onChange={(e) => setForm({ ...form, nameAr: e.target.value })} required /></Field><Field label="رمز الخدمة" hint="إنجليزي صغير مثل confirm_diagnosis"><Input value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value.toLowerCase().replace(/\s+/g, "_") })} dir="ltr" className="text-right" required disabled={Boolean(editing)} /></Field><Field label="السعر الأساسي (ريال)"><Input type="number" min={0} step="0.01" value={form.basePrice} onChange={(e) => setForm({ ...form, basePrice: e.target.value })} placeholder="اتركه فارغًا إذا كان حسب الفحص" /></Field><Field label="المدة المقدرة بالدقائق"><Input type="number" min={5} value={form.estimatedMinutes} onChange={(e) => setForm({ ...form, estimatedMinutes: e.target.value })} /></Field><Field label="ترتيب الظهور"><Input type="number" min={0} value={form.sortOrder} onChange={(e) => setForm({ ...form, sortOrder: e.target.value })} /></Field>{editing ? <Field label="الحالة"><select value={form.isActive ? "active" : "inactive"} onChange={(e) => setForm({ ...form, isActive: e.target.value === "active" })} className="focus-ring min-h-12 rounded-xl border border-[#343943] bg-[#111318] px-4"><option value="active">مفعلة</option><option value="inactive">متوقفة</option></select></Field> : null}<div className="sm:col-span-2"><Field label="وصف الخدمة"><Textarea value={form.descriptionAr} onChange={(e) => setForm({ ...form, descriptionAr: e.target.value })} /></Field></div></div>{error ? <div className="mt-4 rounded-xl border border-red-400/20 bg-red-400/8 p-3 text-sm text-red-200">{error}</div> : null}<div className="mt-6 flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => setFormOpen(false)} disabled={busy}>إلغاء</Button><Button type="submit" disabled={busy}>{busy ? <Loader2 className="animate-spin" size={17} /> : null}حفظ الخدمة</Button></div></form></div> : null}
  </>;
}
