"use client";

import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, Copy, Edit3, KeyRound, Loader2, Plus, RefreshCw, UserCog, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Field } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { LoadingBlock } from "@/components/ui/loading";
import { Select } from "@/components/ui/select";
import { roleLabels } from "@/lib/domain/labels";
import type { StaffRole } from "@/lib/domain/types";

type Staff = { id: string; full_name: string; role: StaffRole; is_active: boolean; created_at: string };
type Credentials = { email: string; temporaryPassword: string; fullName: string; role: StaffRole };

export function StaffManager() {
  const [rows, setRows] = useState<Staff[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Staff | null>(null); const [form, setForm] = useState({ fullName: "", email: "", role: "technician" as StaffRole, isActive: true }); const [credentials, setCredentials] = useState<Credentials | null>(null);
  const load = useCallback(async () => { setLoading(true); const response = await fetch("/api/admin/staff", { cache: "no-store" }); const body = await response.json(); if (body.ok) setRows(body.data); else setError(body.error); setLoading(false); }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  function create() { setEditing(null); setForm({ fullName: "", email: "", role: "technician", isActive: true }); setCredentials(null); setOpen(true); }
  function edit(row: Staff) { setEditing(row); setForm({ fullName: row.full_name, email: "", role: row.role, isActive: row.is_active }); setCredentials(null); setOpen(true); }
  async function submit(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(""); const response = await fetch(editing ? `/api/admin/staff/${editing.id}` : "/api/admin/staff", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(editing ? { fullName: form.fullName, role: form.role, isActive: form.isActive } : { fullName: form.fullName, email: form.email, role: form.role }) }); const body = await response.json(); setBusy(false); if (!body.ok) return setError(body.error); if (!editing) setCredentials(body.data); else setOpen(false); await load(); }
  return <><div className="mb-5 flex justify-end gap-2"><Button variant="secondary" onClick={() => void load()}><RefreshCw size={16} /> تحديث</Button><Button onClick={create}><Plus size={17} /> موظف جديد</Button></div>{error ? <div className="mb-4 rounded-xl border border-red-400/20 bg-red-400/8 p-3 text-sm text-red-200">{error}</div> : null}{loading ? <LoadingBlock label="تحميل الموظفين" /> : <div className="grid gap-4 lg:grid-cols-2">{rows.map((row) => <article key={row.id} className="panel rounded-2xl p-5"><div className="flex items-center gap-4"><span className="grid size-11 place-items-center rounded-xl bg-[#FFD100]/10 text-[#FFD100]"><UserCog size={21} /></span><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><strong>{row.full_name}</strong><Badge tone={row.is_active ? "success" : "neutral"}>{row.is_active ? "نشط" : "موقوف"}</Badge></div><p className="mt-1 text-sm text-[#8f96a3]">{roleLabels[row.role]}</p></div><Button variant="ghost" size="sm" onClick={() => edit(row)}><Edit3 size={16} /></Button></div></article>)}</div>}
  {open ? <div className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-4"><button className="absolute inset-0" onClick={() => !busy && setOpen(false)} /><form onSubmit={submit} className="panel relative z-10 w-full max-w-lg rounded-3xl bg-[#111318] p-6"><button type="button" className="absolute left-4 top-4 grid size-9 place-items-center rounded-xl bg-white/5" onClick={() => setOpen(false)}><X size={18} /></button><h2 className="text-xl font-black">{editing ? "تعديل الموظف" : "إنشاء موظف"}</h2>{!credentials ? <div className="mt-6 grid gap-4"><Field label="الاسم"><Input value={form.fullName} onChange={(e) => setForm({ ...form, fullName: e.target.value })} required /></Field>{!editing ? <Field label="بريد تسجيل الدخول"><Input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} dir="ltr" className="text-right" required /></Field> : null}<Field label="الدور"><Select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value as StaffRole })}><option value="receptionist">موظف استقبال</option><option value="technician">فني</option><option value="admin">مدير</option></Select></Field>{editing ? <Field label="الحالة"><Select value={form.isActive ? "active" : "inactive"} onChange={(e) => setForm({ ...form, isActive: e.target.value === "active" })}><option value="active">نشط</option><option value="inactive">موقوف</option></Select></Field> : null}<Button type="submit" disabled={busy}>{busy ? <Loader2 className="animate-spin" size={17} /> : <KeyRound size={17} />} حفظ</Button></div> : <div className="mt-6"><div className="rounded-2xl border border-emerald-400/25 bg-emerald-400/8 p-4"><span className="flex items-center gap-2 font-bold text-emerald-200"><CheckCircle2 size={18} /> تم إنشاء الحساب</span></div><div className="mt-4 grid gap-3"><div className="rounded-xl border border-white/10 p-4"><span className="text-xs text-[#7f8793]">البريد</span><div className="mt-2 flex justify-between"><code dir="ltr">{credentials.email}</code><Button type="button" variant="ghost" size="sm" onClick={() => void navigator.clipboard.writeText(credentials.email)}><Copy size={15} /></Button></div></div><div className="rounded-xl border border-[#FFD100]/25 p-4"><span className="text-xs text-[#a89b4f]">كلمة المرور المؤقتة</span><div className="mt-2 flex justify-between"><code dir="ltr" className="text-[#FFD100]">{credentials.temporaryPassword}</code><Button type="button" variant="ghost" size="sm" onClick={() => void navigator.clipboard.writeText(credentials.temporaryPassword)}><Copy size={15} /></Button></div></div></div><Button type="button" className="mt-5 w-full" onClick={() => setOpen(false)}>تم الحفظ</Button></div>}</form></div> : null}</>;
}
